---
cidr_networks:
  container: 172.29.236.0/22
  storage: 172.29.244.0/22

used_ips:
  - "172.29.236.1,172.29.236.50"
  - "172.29.244.1,172.29.244.50"
  - "172.29.248.1,172.29.248.50"

global_overrides:
  internal_lb_vip_address: 172.29.236.100
  # The external IP is quoted simply to ensure that the .aio file can be used as input
  # dynamic inventory testing.
  external_lb_vip_address: "162.253.42.130"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          - swift_proxy

shared-infra_hosts:
  aio1:
    # Rabbitmq, and galera are set to multiples to test clustering.
    affinity:
      galera_container: 1
      rabbit_mq_container: 1
    ip: 172.29.236.100

os-infra_hosts:
  aio1:
    # Horizon is set to multiple to test clustering. This test only requires x2.
    affinity:
      horizon_container: 1
    ip: 172.29.236.100

storage-infra_hosts:
  aio1:
    ip: 172.29.236.100

repo-infra_hosts:
  aio1:
    # Repo is set to multiple to test clustering. This test only requires x2.
    affinity:
      repo_container: 1
    ip: 172.29.236.100

identity_hosts:
  aio1:
    # Keystone is set to multiple to test clustering. This test only requires x2.
    affinity:
      keystone_container: 1
    ip: 172.29.236.100

compute_hosts:
  aio1:
    ip: 172.29.236.100

storage_hosts:
  aio1:
    ip: 172.29.236.100
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "172.29.236.100"

log_hosts:
  aio1:
    ip: 172.29.236.100

network_hosts:
  aio1:
    ip: 172.29.236.100

haproxy_hosts:
  aio1:
    ip: 172.29.236.100
